### ISSUE TITLE
ModuleNotFoundError: No module named 'csvquery'

### ISSUE THREAD

**Issue by dejkam** [hycsg/csvquery#23]
Hi,
I installed csvquery1.1.3 and the installation process was successful. However, when I try to import the package, import csvquery, then I receive the following error message:
ModuleNotFoundError: No module named 'csvquery'

Is there any dependency that must be installed? How can I solve the issue?
Thanks in advance.

**Comment by furas** [comment]
It seems module is broken.

I downloaded it (1.1.3)

     pip download csvquery

and it get file `csvquery-1.1.3-py3-none-any.whl` which I opened in `zip viewer` and there is no code - no folder `csvquery` with code. 

I did it the same with version 1.1.2

     pip download csvquery==1.1.2

and file `csvquery-1.1.2-py3-none-any.whl` has all code.

**Comment by dejkam** [comment]
Thanks for your kind consideration. It's working now.

**Comment by DGKSK8LIFE** [comment]
yeah. ngl @dejkam @furas, this project was built to learn. I advise you to use pandas or a similar prod. ready library to query csv. Thanks in advance @ me if you need anything
